 
name: ifixit_auto_reply_app
description: تطبيق Flutter تجريبي للرد الآلي على الواتس اب
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  http: ^1.1.0
  shared_preferences: ^2.2.2
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
