on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
          channel: 'stable'

      - name: Flutter pub get
        run: flutter pub get

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk

      # Optional: Release APK signing (requires secrets)
      # - name: Decode keystore
      #   if: ${{ secrets.CM_KEYSTORE != '' }}
      #   run: |
      #     mkdir -p android/app/keystore
      #     echo "${{ secrets.CM_KEYSTORE }}" | base64 -d > android/app/keystore/release.jks
      #     cat > android/key.properties << 'EOF'
      #     storePassword=${{ secrets.CM_KEYSTORE_PASSWORD }}
      #     keyPassword=${{ secrets.CM_KEY_ALIAS_PASSWORD }}
      #     keyAlias=${{ secrets.CM_KEY_ALIAS_USERNAME }}
      #     storeFile=keystore/release.jks
      #     EOF
      # - name: Build release APK
      #   if: ${{ secrets.CM_KEYSTORE != '' }}
      #   run: flutter build apk --release
      # - name: Upload release APK
      #   if: ${{ secrets.CM_KEYSTORE != '' }}
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: app-release
      #     path: build/app/outputs/flutter-apk/app-release.apk
