name: Flutter Android APK

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Flutter (stable)
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Flutter pub get
        run: flutter pub get

      # ⬇️ إنشاء android في مجلد مؤقت ثم نقله فقط (لا نلمس lib/)
      - name: Generate Android scaffold without touching lib/
        run: |
          if [ ! -d "android" ]; then
            flutter create --platforms=android temp_scaffold
            rm -rf android
            mv temp_scaffold/android ./android
            rm -rf temp_scaffold
          fi

      # إذن الإنترنت
      - name: Add INTERNET permission
        run: |
          MANIFEST=android/app/src/main/AndroidManifest.xml
          grep -q 'android.permission.INTERNET' "$MANIFEST" || \
          sed -i 's#<manifest .*#&\n    <uses-permission android:name="android.permission.INTERNET"/>#' "$MANIFEST"

      - name: Build debug APK
        run: flutter build apk --debug

      - name: Upload debug APK
        uses: actions/upload-artifact@v4
        with:
          name: app-debug
          path: build/app/outputs/flutter-apk/app-debug.apk
